name: testproject

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Install Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: "18.2.0"

      - name: Install dependencies
        run: npm install

      - name: Build the React app
        run: npm run build

      - name: Deploy using Nginx
        run: |
          sudo rm -rf /var/www/html/*
          sudo cp -r build/* /var/www/html/
          sudo systemctl restart nginx 
