name: testproject

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

        - name: Copy project to EC2 (excluding .git)
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem
          rsync -avz --exclude='.git' -e "ssh -o StrictHostKeyChecking=no -i key.pem -p ${{ secrets.SSH_PORT }}" ./ ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USERNAME }}/react-app
      

      - name: SSH into EC2 and build+run Docker container
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem -p ${{ secrets.SSH_PORT }} ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/react-app
            docker stop my-react-app || true
            docker rm my-react-app || true
            docker build -t my-react-app .
            docker run -d --name my-react-app -p 80:80 my-react-app
          EOF
