name: testproject

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy project to EC2 (excluding .git, node_modules, etc.)
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem
          rsync -avz \
            --exclude '.git' \
            --exclude 'node_modules' \
            -e "ssh -o StrictHostKeyChecking=no -i key.pem -p ${{ secrets.SSH_PORT }}" \
            ./ ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USERNAME }}/react-app

      - name: SSH and deploy Docker container
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem -p ${{ secrets.SSH_PORT }} ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << EOF
            cd /home/${{ secrets.EC2_USERNAME }}/react-app

            # Remove old container if exists
            docker stop my-react-app || true
            docker rm my-react-app || true

            # Build Docker image
            docker build -t my-react-app .

            # Run container
            docker run -d -p 80:80 --name my-react-app my-react-app
      EOF
