name: testproject

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: "18.2.0"

      - name: Install dependencies
        run: npm install

      - name: Build the React app
        run: npm run build

      - name: Copy build folder to EC2
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem
          scp -o StrictHostKeyChecking=no -i key.pem -P ${{ secrets.SSH_PORT }} -r build/* ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/tmp/react-build/

      - name: SSH and deploy to Nginx on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem -p ${{ secrets.SSH_PORT }} ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
            sudo rm -rf /var/www/html/*
            sudo cp -r /tmp/react-build/* /var/www/html/
            sudo systemctl restart nginx
          EOF
